### ISSUE TITLE
Code has bug

### ISSUE THREAD

**Issue by Assassinswhh** [gasmichel/PathNNs_expressive#2]
Hello, it will appear when I run ogbg-molhiv_sp.sh and all ogbg scripts，May I ask why?

Traceback (most recent call last):
  File "/home/wanghonghao/PathNNs_expressive-main/benchmarks/scripts/../main_ogb.py", line 260, in <module>
    main()
  File "/home/wanghonghao/PathNNs_expressive-main/benchmarks/scripts/../main_ogb.py", line 145, in main
    dataset = get_dataset(args.dataset, params['cutoff'], args.path_type, args.output_dir)
  File "/home/wanghonghao/PathNNs_expressive-main/benchmarks/preprocess_data.py", line 549, in get_dataset
    data = PygGraphPropPredDataset(
  File "/home/wanghonghao/.conda/envs/pathnn/lib/python3.9/site-packages/ogb/graphproppred/dataset_pyg.py", line 66, in __init__
    super(PygGraphPropPredDataset, self).__init__(self.root, transform, pre_transform)
  File "/home/wanghonghao/.conda/envs/pathnn/lib/python3.9/site-packages/torch_geometric/data/in_memory_dataset.py", line 55, in __init__
    super().__init__(root, transform, pre_transform, pre_filter, log)
  File "/home/wanghonghao/.conda/envs/pathnn/lib/python3.9/site-packages/torch_geometric/data/dataset.py", line 94, in __init__
    self._process()
  File "/home/wanghonghao/.conda/envs/pathnn/lib/python3.9/site-packages/torch_geometric/data/dataset.py", line 211, in _process
    self.process()
  File "/home/wanghonghao/.conda/envs/pathnn/lib/python3.9/site-packages/ogb/graphproppred/dataset_pyg.py", line 127, in process
    additional_node_files = self.meta_info['additional node files'].split(',')
AttributeError: 'float' object has no attribute 'split'

**Comment by gasmichel** [comment]
Hello, 

It seems that upgrading your ogb version does the trick, you can simply run:

pip install -U ogb

**Comment by Assassinswhh** [comment]
> Hello,
> 
> It seems that upgrading your ogb version does the trick, you can simply run:
> 
> pip install -U ogb

Thank you, the issue has been resolved after the upgrade.
